config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings

  resources :reservations

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :listing
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	include Clearance::User
	has_many :authentications, dependent: :destroy
  has_many :listings
  has_many :reservations
  enum roles: [ :customer, :moderator, :superadmin ]


 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_listing, except: [:index, :new, :create]
	before_action :require_login

	def index
		@listings = Listing.all
		@listings = @listings.state(params[:state]) if params[:state].present?
    	@listings = @listings.country(params[:country]) if params[:country].present?
    	@listings = @listings.available_from(params[:available_from]) if params[:available_from].present?
    	@listings = @listings.available_to(params[:available_to]) if params[:available_to].present?

    	if !params[:min].present? && !params[:max].present?
	      @listings = @listings.where(price: 0..Listing.maximum("price"))
	    elsif params[:min].present? && !params[:max].present?
	      @listings = @listings.where(price: params[:min].to_i..Listing.maximum("price"))
	    elsif params[:max].present? && !params[:min].present?
	      @listings = @listings.where(price: 0..params[:max].to_i)
	    else
	      @listings = @listings.where(price: params[:min].to_i..params[:max].to_i)
	    end



		@listings = @listings.order(id: :asc).page(params[:page])

		# respond_to do |format|
		# 	format.html {render action: "index"}
		# 	format.js
		# end
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to listing_path(@listing), notice: "You have successfully listed your property!"
		else
			render :new, error: "Unfortunately an error has occured, please try creating your listing again!"
		end
	end

	def show	
	end

	def edit
	end

	def update
		if @listing.update(listing_params)
			redirect_to listing_path(@listing), notice: "Your listing has been updated!"
		else
			render :edit, error: "An error has occured, your attempt to update your listing was unsuccessful!"
		end
	end

	def destroy
		@listing.destroy
		redirect_to listing_path, notice: "You have successfully removed your listing!"
	end

	private

	def set_listing
		@listing = Listing.find(params[:id])
	end

	def listing_params
		params.require(:listing).permit(
			:name,
			:description,
			:address,
			:state,
			:country,
			:number_of_beds,
			:price,
			:available_from,
			:available_to,
			:property_type,
			:images => []
			)
	end

	def authorize_user
		redirect_to listings_path if current_user.customer? && current_user != listing.user
	end

	def verify
        if current_user.superadmin? || current_user.moderator?
            @listing.update(verified: true)
            redirect_to listing_path(@listing.id)
        else
            redirect_to "/"
            flash[:alert] = "NO"
        end
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "You have successfully signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = edit_user_path(user)
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:index]
  	before_action :check_role, only: [:edit, :update, :destroy]
  	before_action :require_login

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
	end

	def destroy
	end

	def edit
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path
	end

	def index
		if !current_user.superadmin? && !signed_in?
			redirect_to "/"
			flash[:error] = "NO"
		else
			@users = User.order(:id).page(params[:page])
			# respond_to do |format|
			# 	format.html {render action: "index"}
			# 	format.js
			# end
		end
	end

private
	def user_params
		params.require(:user).permit(
			:first_name,
			:last_name,
			:email,
			:password,
			:role,
			:avatar
		)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def check_role
		redirect_to root_path if !current_user.superadmin? && current_user != @user
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :require_login

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2" %>

    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/listings/_form.html.erb
<div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, type: 'text', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, type: 'text', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, type: 'text', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, type: 'text', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :country %>
        <%= form.text_field :country, type: 'text', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :number_of_beds %>
        <%= form.number_field :number_of_beds, type: 'number', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :price %>
        <%= form.number_field :price, type: 'number', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :available_from %>
        <%= form.date_field :available_from, type: 'date', min: Date.today, class: "form-control" %>
    </div>


    <div class="form-group">
        <%= form.label :available_to %>
        <%= form.date_field :available_to, type: 'date', min: Date.today + 1, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.file_field :images, type:'file', multiple: true, class:"form-control-file" %>
    </div>

app/views/listings/_index.html.erb
<%= paginate @listings %>
<table>
	<tr>
		<th>ID</th>
		<th>Host ID</th>
		<th>Name</th>
		<th>Description</th>
		<th>Address</th>
		<th>State</th>
		<th>Country</th>
		<th>Number Of Beds</th>
		<th>Price</th>
		<th>Date Available From</th>
		<th>Date Available Till</th>
		<th>Property Type</th>
		
	</tr>

	<% @listings.each do |l| %>

	<tr>
		<td><%= l.id %></td>
		<td><%= l.user_id %></td>
		<td><%= l.name %></td>
		<td><%= l.description %></td>
		<td><%= l.address %></td>
		<td><%= l.state %></td>
		<td><%= l.country %></td>
		<td><%= l.number_of_beds %></td>
		<td><%= l.price %></td>
		<td><%= l.available_from %></td>
		<td><%= l.available_to %></td>
		<td><%= l.property_type %></td>
	</tr>


	<% end %>
</table>
<%= paginate @listings %>

app/views/listings/edit.html.erb
    <h1>Edit Listings</h1>
    <%= form_with model: @listing, local: true do |form| %>
    
    <%= render partial: "listings/form", object: form %>

    <div>
        <%= form.submit class: "btn btn-primary"%>
    </div>
    <% end %>

app/views/listings/index.html.erb
<div id="listing-container">
  <%= render "listings/index" %>
</div>

app/views/listings/new.html.erb
<h1> Create your listing! </h1>

    <%= form_with model: Listing.new, local: true do |form| %>
    
    <%= render partial: "listings/form", object: form %>
    
    <button type="submit" class="btn btn-primary">Create Listing</button>
    <% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2><%= "Welcome #{@user.first_name} #{@user.last_name}! Below are your listings!" %></h2>

<% @user.listings.each do |l| %>
	<h3><%= l.name %> $<%= l.price %> Beds: <%= l.number_of_beds %> Country: <%= l.country %></h3>
	<%= button_to "Delete", listing_path(l.id), method: "delete" %>
	<%= button_to "Edit", edit_listing_path(l.id), method: "get" %>
<% end %>

app/views/welcome/index.html.erb
<h1> Welcome to the AirBnB Homepage! </h1>

<%= link_to "Create New Listing", new_listing_path %>
<%= link_to "View All Listings", listings_path %>
<%= link_to "View Profile", user_path(current_user.id) %>